- name: USER | Create group
  ansible.builtin.group:
    name: clement
    gid: 1000

- name: USER | Create user
  user:
    name: clement
    group: clement
    groups: [ wheel ]
    shell: /usr/bin/fish
    password: '{{ user_password }}'
    uid: 1000

- name: USER | Give passwordless sudo access to wheel group
  copy:
    content: '%wheel ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/wheel
    mode: 0440
    validate: /usr/sbin/visudo --check --file=%s

- name: USER | Switch to non root user
  set_fact:
    ansible_chroot_exe: /tmp/ansible-arch-install-chroot
    ansible_remote_tmp: /home/clement/.ansible/tmp